####Train GradientBoostingRegressor for several learning rates and select the best by validation MSE.


# Grade Cell: Question 9
#
# Task: Boosting with validation selection.
#
# Instructions:
# 1. Create a train/validation split from the original training set (e.g., 30% as validation; random_state=RANDOM_STATE).
# 2. For learning rates in `[1.0, 0.1, 0.03]`, fit `GradientBoostingRegressor(n_estimators=300, max_depth=1, random_state=RANDOM_STATE)` and record train and validation MSE over staged predictions.
# 3. Determine `best_params_gbr` as a dict with keys `learning_rate` and `best_iter` (iteration minimizing validation MSE).
# 4. Fit a final model with that learning rate and `n_estimators=best_iter` on the full training set and compute `mse_gbr_test` on TEST.
#
# Use the output splits generated by split_regression_data() in Question 2.

X_tr, X_val, y_tr, y_val = train_test_split(
    X_train, y_train, test_size=0.25, random_state=RANDOM_STATE
)

learning_rates = [0.01, 0.05, 0.1, 0.2, 0.5]
n_estimators = 200

gbr_results: Dict = {}
best_overall = {"val_mse": np.inf, "learning_rate": None, "best_iter": None}

for lr in learning_rates:
    gbr = GradientBoostingRegressor(
        learning_rate=lr,
        n_estimators=n_estimators,
        random_state=RANDOM_STATE,
    )
    gbr.fit(X_tr, y_tr)

    val_mses = [mean_squared_error(y_val, pred) for pred in gbr.staged_predict(X_val)]
    best_iter_lr = int(np.argmin(val_mses)) + 1
    best_val_mse_lr = float(val_mses[best_iter_lr - 1])

    gbr_results[lr] = {"val_mse": best_val_mse_lr, "best_iter": best_iter_lr}
    print(f"lr={lr:<5} -> best_iter={best_iter_lr:>3}, val_MSE={best_val_mse_lr:.2f}")

    if best_val_mse_lr < best_overall["val_mse"]:
        best_overall = {"val_mse": best_val_mse_lr, "learning_rate": lr, "best_iter": best_iter_lr}

best_params_gbr: Dict = {
    "learning_rate": best_overall["learning_rate"],
    "best_iter": int(best_overall["best_iter"]),
}
print(f"\nbest_params_gbr: {best_params_gbr}")

best_gbr = GradientBoostingRegressor(
    learning_rate=best_params_gbr["learning_rate"],
    n_estimators=best_params_gbr["best_iter"],
    random_state=RANDOM_STATE,
)
best_gbr.fit(X_train, y_train)
mse_gbr_test = mean_squared_error(y_test, best_gbr.predict(X_test))
print(f"Best GBR — Test MSE={mse_gbr_test:.2f}")
