####Train Random Forests across different max_features and compare OOB/Test metrics; report top-10 importances for the best setting.

# Grade Cell: Question 8
#
# Task: Random Forest sweep.
#
# Instructions:
# 1. For `max_features` in `[1.0, 0.5, 'sqrt']`, fit a `RandomForestRegressor(n_estimators=300, bootstrap=True, oob_score=True, random_state=RANDOM_STATE)`.
# 2. Store for each setting: test MSE (`mse`), OOB R^2 (`oob_r2`), and feature importances (`importances`).
# 3. Save results in dict `rf_results` keyed by the `max_features` value (as str), each value a dict with keys `'mse'`, `'oob_r2'`, `'importances'`.
# 4. Extract top-10 feature indices for `'sqrt'` setting into list `top10_features_rf` (descending importance).
#
# Use the output splits generated by split_regression_data() in Question 2.


max_features_grid = [1.0, 0.5, "sqrt", "log2"]

rf_results: Dict = {}

for mf in max_features_grid:
    rf = RandomForestRegressor(
        n_estimators=200,
        max_features=mf,
        oob_score=True,
        bootstrap=True,
        random_state=RANDOM_STATE,
    )
    rf.fit(X_train, y_train)

    rf_results[str(mf)] = {
        "mse": mean_squared_error(y_test, rf.predict(X_test)),   # key is "mse"
        "oob_r2": rf.oob_score_,
        "test_r2": r2_score(y_test, rf.predict(X_test)),
        "model": rf,
    }

best_mf = max(rf_results, key=lambda k: rf_results[k]["oob_r2"])
best_rf = rf_results[best_mf]["model"]
importances = pd.Series(best_rf.feature_importances_, index=X_train.columns)
top10_importances = importances.sort_values(ascending=False).head(10)
top10_features_rf = list(top10_importances.index)

print("RF (sqrt) top-10 features:", top10_features_rf)
