####Compare a bagged ensemble to the baseline single tree using OOB and test metrics.


# Grade Cell: Question 7
#
# Task: Bagging for regression.
#
# Instructions:
# 1. Fit `BaggingRegressor(DecisionTreeRegressor(random_state=RANDOM_STATE), n_estimators=200, bootstrap=True, oob_score=True, random_state=RANDOM_STATE)`.
# 2. Compute `mse_bag` on TEST and record `oob_r2_bag`.
#
# Use the output splits generated by split_regression_data() in Question 2.

bag_reg = BaggingRegressor(
    base_estimator=DecisionTreeRegressor(random_state=RANDOM_STATE),
    n_estimators=100,
    oob_score=True,
    bootstrap=True,
    random_state=RANDOM_STATE,
)
bag_reg.fit(X_train, y_train)

oob_r2_bag = bag_reg.oob_score_
y_pred_bag = bag_reg.predict(X_test)
mse_bag = mean_squared_error(y_test, y_pred_bag)
r2_bag_test = r2_score(y_test, y_pred_bag)

print(f"Bagging: Test MSE={mse_bag:.2f}, OOB R2={oob_r2_bag:.3f}")
