####Use permutation importance and PDP/ICE on the classification dataset with RF and GBM


# Grade Cell: Question 10
#
# Task: Global and local interpretation on classification.
#
# Instructions:
# 1. Fit `RandomForestClassifier(n_estimators=300, max_features='sqrt', random_state=RANDOM_STATE)` and `GradientBoostingClassifier(learning_rate=0.1, n_estimators=250, max_depth=1, random_state=RANDOM_STATE)`.
# 2. Compute permutation importance on the TEST set for both; store arrays in `perm_importance_rf` and `perm_importance_gb`.
# 3. Select the top-1 feature index from RF, store as `pdp_feature_index` and generate PDP+ICE plots for that feature for RF and GBM (plots not graded).
#
# Use the output splits generated by split_classification_data() in Question 5."
# 1. Fit both classifiers with the exact hyperparameters specified

rf_clf = RandomForestClassifier(n_estimators=300, max_features="sqrt", random_state=RANDOM_STATE)
rf_clf.fit(X_train_cls, y_train_cls)

gb_clf = GradientBoostingClassifier(learning_rate=0.1, n_estimators=250, max_depth=1, random_state=RANDOM_STATE)
gb_clf.fit(X_train_cls, y_train_cls)

perm_rf = permutation_importance(rf_clf, X_test_cls, y_test_cls, n_repeats=10, random_state=RANDOM_STATE)
perm_gb = permutation_importance(gb_clf, X_test_cls, y_test_cls, n_repeats=10, random_state=RANDOM_STATE)

perm_importance_rf = perm_rf.importances_mean
perm_importance_gb = perm_gb.importances_mean

pdp_feature_index = int(np.argmax(perm_importance_rf))
print(f"Top RF feature index: {pdp_feature_index} ({X_train_cls.columns[pdp_feature_index]})")

fig, ax = plt.subplots(1, 2, figsize=(12, 5))

PartialDependenceDisplay.from_estimator(
    rf_clf, X_test_c, features=[pdp_feature_index],
    kind="both", ax=ax[0],   # "both" = PDP line + ICE curves
)
ax[0].set_title("Random Forest")

PartialDependenceDisplay.from_estimator(
    gb_clf, X_test_c, features=[pdp_feature_index],
    kind="both", ax=ax[1],
)
ax[1].set_title("Gradient Boosting")

plt.tight_layout()
plt.show()
